=== kraleksandr/l2jz-ru/www/engine/dtd/languageRoot.dtd
<!--
-->
<!ELEMENT languageRoot (h)*>
<!ATTLIST languageRoot
  name    CDATA #IMPLIED
>

<!ELEMENT h (#PCDATA|h)*>
<!ATTLIST h
  name    CDATA #REQUIRED
  value   CDATA #IMPLIED
>

=== kraleksandr/l2jz-ru/www/modules/account/Languages/english.lng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE languageRoot SYSTEM "../../../engine/dtd/languageRoot.dtd">
<languageRoot>
    <h name="page.account">
        <h name="main.linkName" value="Main"/>
    </h>
    <h name="query">
        <h name="account">
            <h name="chars">
                <h name="empty" value="There are no chars on this account."/>
            </h>
            <h name="action">
                <h name="moveCharToAccount">
                    <h name="ok" value="Char was succesfully moved to another account."/>
                    <h name="error:fullAccount" value="There are allready seven chars on this account."/>
                    <h name="error:noSuchChar" value="There is no char with such name."/>
                </h>
                <h name="changePass">
                    <h name="ok" value="Password was successfully changed."/>
                </h>
                <h name="changeMyPass">
                    <h name="ok" value="Password was successfully changed."/>
                    <h name="error:wrongLoginOrPass" value="Incorrect login or password."/>
                </h>
                <h name="changeAccess">
                    <h name="ok" value="Access level was successfully changed."/>
                </h>
                <h name="changeEmail">
                    <h name="ok" value="Email was successfully changed."/>
                </h>
                <h name="ban">
                    <h name="ok" value="Account was succesfully banned."/>
                </h>
                <h name="unban">
                    <h name="ok" value="Account was succesfully unbanned."/>
                </h>
            </h>
        </h>
    </h>
    <h name="panel.account">
        <h name="changePass" value="Set\nPassword">
            <h name="newPass" value="Password"/>
            <h name="equalError" value="The entered passes are not identical."/>
        </h>
        <h name="changeMyPass" value="Change\nPassword">
            <h name="pass" value="Old Password"/>
            <h name="newPass" value="New Pass"/>
            <h name="newPassAgain" value="New Pass again"/>
            <h name="button" value="Change"/>
            <h name="equalError" value="The entered passes are not identical."/>
        </h>
        <h name="changeAccess" value="Set\nBuilder"/>
        <h name="changeEmail" value="Change\nEmail">
            <h name="email" value="Email Address"/>
            <h name="button" value="Change"/>
        </h>
        <h name="moveCharToAccount" value="Move char to\nThis Account">
            <h name="char_name" value="Char name"/>
            <h name="login" value="Account"/>
            <h name="button" value="Move"/>
        </h>
        <h name="ban">
            <h name="button" value="Ban"/>
        </h>
        <h name="unban">
            <h name="button" value="Unban"/>
        </h>
    </h>
</languageRoot>

=== kraleksandr/l2jz-ru/www/modules/server/Languages/english.lng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE languageRoot SYSTEM "../../../engine/dtd/languageRoot.dtd">
<languageRoot>
	<h name="page.server.main">
		<h name="linkName" value="@:sT.GS.name:@"/>
		<h name="title" value="@:sT.GS.name:@"/>
	</h>
	<h name="table">
		<h name="server">
			<h name="rateXp" value="Exp"/>
			<h name="rateSp" value="Sp"/>
			<h name="rateDropAdena" value="Adena"/>
			<h name="rateDropItems" value="Drop"/>
			<h name="rateDropSpoil" value="Spoil"/>
			<h name="char_count" value="Total Chars"/>
			<h name="acc_count" value="Total Accounts"/>
			<h name="adena_count" value="Total Adena"/>
			<h name="sum_level" value="Average Level"/>
		</h>
	</h>
</languageRoot>

=== kraleksandr/l2jz-ru/www/modules/map/Languages/english.lng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE languageRoot SYSTEM "../../../engine/dtd/languageRoot.dtd">
<languageRoot>
	<h name="page.map">
		<h name="linkName" value="@@CDATA@@"><![CDATA[<img src="i/locate.gif" width="14" border="0">]]></h>
		<h name="mainMenu" value="Map"/>
		<h name="chars_online.linkName" value="Chars Online"/>
	</h>
	<h name="query.map">
		<h name="chars_online">
			<h name="empty" value="No chars online."/>
		</h>
	</h>
</languageRoot>

=== kraleksandr/l2jz-ru/www/modules/char/Languages/english.lng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE languageRoot SYSTEM "../../../engine/dtd/languageRoot.dtd">
<languageRoot>
    <h name="page.char">
        <h name="main.linkName" value="Main"/>
        <h name="inventory.linkName" value="Inventory"/>
        <h name="skills.linkName" value="Skills"/>
        <h name="friends.linkName" value="Friends"/>
        <h name="recipebook.linkName" value="Recipe Book"/>
    </h>
	<h name="query.char">
		<h name="inventory">
			<h name="empty" value="No items."/>
		</h>
	</h>
    <h name="panel.char">
        <h name="main">
            <h name="kick">
                <h name="button" value="Kick"/>
            </h>
            <h name="changeAccess" value="Set\nBuilder"/>
            <h name="sendWhisper" value="Send\nWhisper">
                <h name="whisper" value="Whisper text"/>
                <h name="button" value="Send"/>
            </h>
            <h name="changeClass" value="Set\nClass">
                <h name="class_id" value="Class"/>
            </h>
            <h name="changeName" value="Change\nName">
                <h name="char_name" value="New name"/>
                <h name="button" value="Change"/>
            </h>
            <h name="teleport" value="Teleport\nChar">
                <h name="xyz" value="X  Y  Z"/>
                <h name="button" value="Go"/>
            </h>
            <h name="moveToAccount" value="Move Char\nTo Account">
                <h name="login" value="Account"/>
                <h name="button" value="Move"/>
            </h>
        </h>
        <h name="skills">
            <h name="addSkill" value="Add\nSkill">
                <h name="skill_id" value="Skill ID"/>
                <h name="skill_level" value="Level"/>
            </h>
            <h name="deleteSkill">
                <h name="button" value="Delete"/>
            </h>
        </h>
        <h name="item">
            <h name="addItem" value="Add\nitem">
                <h name="count" value="Count"/>
                <h name="button" value="Add"/>
            </h>
            <h name="deleteItem">
                <h name="button" value="Delete"/>
            </h>
        </h>
    </h>
    <h name="etc">
            </h>
</languageRoot>

=== kraleksandr/l2jz-ru/www/modules/quickAsk/Languages/english.lng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE languageRoot SYSTEM "../../../engine/dtd/languageRoot.dtd">
<languageRoot>
	<h name="query">
		<h name="quickAsk">
            <h name="search">
                <h name="char">
                    <h name="empty" value="No such char."/>
                </h>
                <h name="item">
                    <h name="empty" value="No such item."/>
                </h>
                <h name="mob">
                    <h name="empty" value="No such mob."/>
                </h>
            </h>
        </h>
	</h>
</languageRoot>

=== kraleksandr/l2jz-ru/www/modules/account/Languages/russian.lng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE languageRoot SYSTEM "../../../engine/dtd/languageRoot.dtd">
<languageRoot>
    <h name="page.account">
        <h name="main.linkName" value="Главная панель"/>
    </h>
    <h name="query">
        <h name="account">
            <h name="chars">
                <h name="empty" value="Нет чаров на этом акаунте."/>
            </h>
            <h name="action">
                <h name="moveCharToAccount">
                    <h name="ok" value="Персонаж был перенесен на другой акаунт."/>
                    <h name="error:fullAccount" value="Этот акаунт уже полон."/>
                    <h name="error:noSuchChar" value="Персонаж с таким именем не найден."/>
                </h>
                <h name="changePass">
                    <h name="ok" value="Пароль был изменен."/>
                </h>
                <h name="changeMyPass">
                    <h name="ok" value="Пароль был изменен."/>
                    <h name="error:wrongLoginOrPass" value="Неправильный логин или пароль."/>
                </h>
                <h name="changeAccess">
                    <h name="ok" value="Уровень доступа был изменен."/>
                </h>
                <h name="changeEmail">
                    <h name="ok" value="Email был изменен."/>
                </h>
                <h name="ban">
                    <h name="ok" value="Акаунт забанен."/>
                </h>
                <h name="unban">
                    <h name="ok" value="Акаунт разбанен."/>
                </h>
            </h>
        </h>
    </h>
    <h name="panel.account">
        <h name="changePass" value="Установить\nПароль">
            <h name="newPass" value="Пароль"/>
            <h name="equalError" value="Введенные пароли не совпадают."/>
        </h>
        <h name="changeMyPass" value="Смена\nпароля">
            <h name="pass" value="Старый пароль"/>
            <h name="newPass" value="Новый пароль"/>
            <h name="newPassAgain" value="Подтвердить пароль"/>
            <h name="button" value="Изменить"/>
            <h name="equalError" value="Введенные пароли не совпадают."/>
        </h>
        <h name="changeAccess" value="Установить\nBuilder"/>
        <h name="changeEmail" value="Изменить\nEmail">
            <h name="email" value="Email"/>
            <h name="button" value="Изменить"/>
        </h>
        <h name="moveCharToAccount" value="Перенести персонажа\nна этот акаунт">
            <h name="char_name" value="Имя персонажа"/>
            <h name="login" value="Акаунт"/>
            <h name="button" value="Переместить"/>
        </h>
        <h name="ban">
            <h name="button" value="Бан"/>
        </h>
        <h name="unban">
            <h name="button" value="Разбанить"/>
        </h>
    </h>
</languageRoot>

=== kraleksandr/l2jz-ru/www/modules/castles/Languages/english.lng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE languageRoot SYSTEM "../../../engine/dtd/languageRoot.dtd">
<languageRoot>
	<h name="page">
		<h name="castles">
            <h name="table">
				<h name="linkName" value="Castles"/>
				<h name="tooltip" value="Here you can see information about castles."/>
			</h>
			<h name="map.linkName" value="Siege Map"/>
        </h>
	</h>
    <h name="table">
        <h name="castle">
            <h name="taxPercent" value="Tax Rate"/>
            <h name="siegeDate" value="Next Siege Date"/>
            <h name="owner_id" value="Owner"/>
            <h name="attackers" value="Attackers"/>
            <h name="defenders" value="Defenders"/>
        </h>
    </h>
</languageRoot>

=== kraleksandr/l2jz-ru/www/modules/drop/Languages/english.lng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE languageRoot SYSTEM "../../../engine/dtd/languageRoot.dtd">
<languageRoot>
    <h name="page">
        <h name="item">
            <h name="main.linkName" value="Main"/>
            <h name="drop.linkName" value="Drop"/>
            <h name="sell.linkName" value="Shop"/>
            <h name="recipe.linkName" value="Recipe"/>
            <h name="owners.linkName" value="Owners"/>
        </h>
        <h name="monster">
            <h name="main.linkName" value="Main"/>
            <h name="skills.linkName" value="Skills"/>
            <h name="minions.linkName" value="Minions"/>
        </h>
    </h>
    <h name="table">
        <h name="recipe">
            <h name="level" value="Level"/>
            <h name="count" value="Quantity"/>
            <h name="chance" value="Chance"/>
            <h name="mp" value="MP"/>
            <h name="calculator_name" value="Crafting Price"/>
            <h name="total" value="Total"/>
        </h>
    </h>
    <h name="panel.drop">
        <h name="recipe">
            <h name="calculate">
                <h name="button" value="Calculate"></h>
            </h>
        </h>
    </h>
</languageRoot>
